# Generated by Django 3.1.3 on 2020-11-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='details',
            new_name='detail',
        ),
    ]
