# Generated by Django 3.1.3 on 2020-11-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_auto_20201121_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='detail',
        ),
    ]
